# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-EncryptedHash
version:      1.24
version_from: 
installdirs:  site
requires:
    Crypt::Blowfish:               0
    Crypt::CBC:                    0
    Crypt::DES:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
